### PR TITLE
Redirect to sign-in full page

### PR DESCRIPTION
**Pull request by un-tone**
For https://github.com/StarcounterApps/SignIn/issues/89

### CODE REVIEW

**Comment by un-tone** [comment]
Though it works well on my side there is some problem with blending (I suppose) when Website is not runnning (only SignIn and UserAdmin are).
I get such view in this case:
image

But after page refreshing I get the following:
image

Both of this views are incorrect. I investigated this issue earlier but still haven't found a reason.

@warpech could you look at this too please?

**Comment by warpech** [comment]
On the first screenshot, UserAdmin includes a nested view from UserAdmin. That view is blended with a view from SignIn. The SignIn view forces a client-side**redirection** to `GET /signin/signinuser?%2fUserAdmin%2fadmin%2fusers`.

That request is handled by https://github.com/StarcounterApps/SignIn/blob/16bd6e83e74db64f29e825fcc5fb162da9150d48/src/SignIn/Api/MainHandlers.cs#L243-L261, which returns `master`. This response is supposed to be returned on the root level (and replace previous root response from UserAdmin). 

But, unless you add `Session.Current.PublicViewModel = master;` before https://github.com/StarcounterApps/SignIn/blob/16bd6e83e74db64f29e825fcc5fb162da9150d48/src/SignIn/Api/MainHandlers.cs#L260, you don't see that response at all. You are stuck with UserAdmin's JSON at the root and you get an empty patch to it:

2017-06-30 14_38_25-greenshot

@chrhol is this solved by https://github.com/Starcounter/Home/issues/137?

@un-tone since we are pushing WebsiteProvider on our users, maybe we can assume this now only has to work with WebsiteProvider and make a separate issue for working standalone? Is there anything else to do then?

**Comment by un-tone** [comment]
I will create another issue to fix the problem with standalone mode. If you approve that this PR resolves the issue #111 I assume I could merge it and close the issue.

**Comment by chrhol** [comment]
> @chrhol is this solved by Starcounter/Home#137?

It would have been solved, but due to the problems described in https://github.com/Starcounter/Home/issues/137#issuecomment-311875049 I had to disable the auto-detection of changes in root, So unfortunately current status is that it will not be solved, at least not in the current iteration.

**Comment by chrhol** [comment]
I think I need to redact my last comment. I think I made an incorrect assumption that SignIn did some weird stuff, when it actually did exactly what was intended: replacing root on logout. If that is the case, then I change my answer for the question from @warpech to: Yes it will be solved with  https://github.com/Starcounter/Home/issues/137

**Comment by un-tone** [comment]
Thanks @warpech

**Pull request merged**
