### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by Mackiovello**
Main changes:
* Shorten lines that were absurdly long and that couldn't be read on my laptop without horizontal scrolling
* Replace `First` with `FirstOrDefault()`

### CODE REVIEW

**Comment by PatrykSzwer** [comment]
I think we agreed to fixed, corresponding file localization namespaces, not the shorter ones. Yet everywhere there are incorrect namespaces, like `SignIn` instead of `SignIn.Helpers`. Please change it if You can or create separated issue for this.

**Comment by PatrykSzwer** [comment]
8. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/Helpers/SignInJwt.cs about this file:
Enum should be moved to separated class. 
L21 and L22 should be made readonly.
L133 string.Format should be replaced with string interpolation.
9. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/Helpers/Utils.cs#L84 string interpolation.
10. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/Models/SystemAdminUser.cs#L15 all fields here have incorrect names. e.g `_adminGroupName` should be `AdminGroupName`.  Also between lines 28-31 unnecessary gap. 

Let's stick with those changes for now. Then I'll check the viewmodels.

**Comment by Mackiovello** [comment]
Dang, you're detail oriented! I fixed everything you requested and a couple things more that I found in the process. 

Also, I chose to use private properties with getters instead of readonly fields. They are more versatile for dependency injection.

**Comment by Mackiovello** [comment]
Are you sure you've done a `git pull`? It's building on TeamCity and locally

**Comment by PatrykSzwer** [comment]
I had some obsolete generated files which caused that problems, nvm, I've fixed that.

**Comment by PatrykSzwer** [comment]
So, now about view models:
1. Folder `viewModels` doesn't apply to our accepted folders structure https://docs.starcounter.io/cookbook/project-structure/ . Should be renamed to `views`
2. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/MasterPage.json.cs#L15 should be renamed to `Url`
3. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/RestorePasswordFormPage.json.cs#L17 null propagation should be used here.
4. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/RestorePasswordFormPage.json.cs#L50 there are sequentional checks that can be merged like this:
`if (person == null || string.IsNullOrEmpty(email?.EMail))`
also in same file, in line 78 method arguments are in uppercase. Lowercase should be used.
5. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/SettingsPage.json.cs#L56 modifiers declaration order is wrong. Should be `protected virtual`
6. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/SignInFormPage.json.cs#L26 null propagation again.
7. https://github.com/StarcounterApps/SignIn/blob/develop/src/SignIn/ViewModels/SystemUserAuthenticationSettings.json.cs#L15 there is obsolete binding used here and in corresponding json file.

I think that's all what I can found.

**Comment by Mackiovello** [comment]
> Folder viewModels doesn't apply to our accepted folders structure https://docs.starcounter.io/cookbook/project-structure/ . Should be renamed to views

This doesn't seem to be right. The folder in `wwwroot/appname` is called "views" as it should

**Comment by PatrykSzwer** [comment]
> Dang, you're detail oriented! 

You bet I'm! That's why everyone's scared of assigning me to PR's like this as reviewer 😆

**Comment by Mackiovello** [comment]
Was that an approval @PatrykSzwer?

**Comment by PatrykSzwer** [comment]
I wasn't sure if You finished. I'll check it right now.

**Pull request merged**
