### PR TITLE
Declarative shadow dom. #36

### PR DESCRIPTION
**Pull request by joozek78**
Currently all but SignInPage.html

### CODE REVIEW

**Comment by joozek78** [comment]
@warpech please look. [SignInPage.html](https://github.com/StarcounterApps/SignIn/blob/36-declarative-shadow-dom/src/SignIn/wwwroot/SignIn/viewmodels/SignInPage.html) has not been transformed yet, but there's probably a lot of CSS issues already :) I'd like to de-duplicate the CSS (`signin-table` and `signin-area`), but I don't know how to achieve it without namespace pollution. Can you help here?

**Comment by warpech** [comment]
I cannot find `signin-table` and `signin-area` in the source code. Can you pls call me on HO to show what is it about?

**Comment by warpech** [comment]
I propose to rename the CSS classes a bit:

```css
.signin                        -> .signin-page
.signin__table                 -> .signin-form
.signin__row                   -> .signin-form__row
.signin__label                 -> .signin-form__label
.signin__input                 -> .signin-form__control
.signin__label ::content label -> .signin-form__control ::content label
.signin__area                  -> .signin-toolbar
```

To make it DRY, stylesheet can be imported to declarative Shadow DOM like here: https://github.com/StarcounterApps/Images/blob/58f41289642ea1b61112c87d6cd8ec38f8d9d34c/src/Images/wwwroot/Images/viewmodels/EditableIllustrationsPage.html#L35

**Comment by warpech** [comment]
Related: https://github.com/Starcounter/Docs/issues/28

**Comment by joozek78** [comment]
Cool, I'll do that

**Comment by joozek78** [comment]
@warpech PTAL

**Comment by warpech** [comment]
I still experience the same problem as on screenshot made by @tomalec:

image

Isn't this supposed to look exactly like before, just with proper separation of content and presentation?

**Comment by warpech** [comment]
This PR implements: https://github.com/StarcounterApps/SignIn/issues/36

**Comment by joozek78** [comment]
Hmm, it looks suspicious. I'll take my own screenshot and then we'll compare!

**Comment by joozek78** [comment]
For me it looks like this:
image
If you look at the [changes](https://github.com/StarcounterApps/SignIn/pull/72/files#diff-811c3b3ab68899762803273081dc3075R68) you'll see that "Remember me" checkbox and the buttons are in separate divs and should render on separate rows.

**Comment by warpech** [comment]
I think your code is right. In SWO Portal there are some hardcoded styles that make it look different.

**Comment by warpech** [comment]
Could you also add slot names to `SignInPage.html`?

**Comment by joozek78** [comment]
The thing is, I don't know how to handle `SignInPage.html` - that's why I haven't touched it. If I just add slot names, won't it break anything?

**Comment by warpech** [comment]
> If I just add slot names, won't it break anything?

No, it won't. It will just be nicer to use in blending.

**Comment by joozek78** [comment]
Please note: [here](https://github.com/StarcounterApps/SignIn/pull/72/files#diff-13b0b2de614e7894baa826c4e4e4bef0R82)

**Comment by joozek78** [comment]
Sooo... I guess we don't want any slots here?

**Comment by warpech** [comment]
We want a slot name on line 76.

**Pull request merged**
